### ISSUE TITLE
CONFLICT_00089

### ISSUE THREAD

**Issue by jseipp** [kerrymcmahon/Frederick-County-Stormwater#2]
**SITE NAME:**
FRGr1-WTB-233

**CONFLICT FEATURE:** HMIS - Ownership

**SITE PHASE:** FIELD INVESTIGATION

**CRM RECOMMENDED STATUS:** FYI - PM should review site to determine if it is a conflict or not.

**CONFLICT DESCRIPTION:** Site is within existing SHA ROW but does not appear to be treating drainage from SHA-owned roadway.

![image](https://cloud.githubusercontent.com/assets/11890203/10367470/afc3e70c-6d9e-11e5-8c70-4e61a4b5ce85.png)

**Comment by mparlakian** [comment]
I agree.  Site should be RC'ed.  the drainage area to the facility just collects a piece of the county road (side street).

**Comment by kerrymcmahon** [comment]
I have removed the site from consideration and closed the issues.
