### ISSUE TITLE
CONFLICT_00090

### ISSUE THREAD

**Issue by jseipp** [kerrymcmahon/Frederick-County-Stormwater#3]
**RESEARCH TYPE:** HMIS - OWNERSHIP & ROW

**RESEARCH DESCRIPTION:** Site is not within existing SHA ROW and does not appear to be treating drainage from SHA-owned roadway.

**SITE PHASE:** FI

**SITE NAMES:** FRGr1-WTB-241, FRGr1-WTB-246

**CRM RECOMMENDED STATUS:** FYI - PM should review each site and indicate if it is a conflict or not.

![image](https://cloud.githubusercontent.com/assets/11890203/10368375/e8537ea8-6da2-11e5-817c-0fc6d6879233.png)

**Comment by mparlakian** [comment]
The drainage area does contribute a small amount of SHA impervious to the site.  It is outside ROW and recieves only a small amount of SHA impervious.  It is a very low viability site, but based technically should not be RC'ed.
